spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/clientflux
    username: postgres
    password: Vaifery111


  application:
    name: client

server:
  port: 7015

variables:
  SECRET_KEY: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: WARN
    io.r2dbc.spi: ERROR
    org.springframework.data.r2dbc: ERROR
    org.springframework.r2dbc: ERROR
