spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/micr-synch}
    username: ${DB_USERNAME:qwe}
    password: ${DB_PASSWORD:qwe}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  application:
    name: client

server:
  port: ${SERVER_PORT:7015}

variables:
  SECRET_KEY: ${JWT_SECRET_KEY:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}
  ALLOWED_ORIGIN: ${ALLOWED_ORIGIN:http://localhost:3000}
